title: mkrtchyan.xyz 
email: kristina@mkrtchyan.xyz
description: >- # this means to ignore newlines until "baseurl:"
    my attempt at documenting interests & hobbies
url: "http://mkrtchyan.xyz" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  kristinamkr

host: 0.0.0.0
port: 4001  # remember to ditch

# Build settings
markdown: kramdown
theme: null 
plugins:
  - jekyll-feed

sass:
    style: compressed

defaults:
-
    scope:
        type: posts
        path: _posts
    values:
        is_post: true
        layout: post
        permalink: /blog/:categories/:title/
-
    scope:
        type: pages
        path: _pages
    values:
        is_post: false
        layout: default

include: [_pages]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
